// <auto-generated />
using CoursesAPI.Models;
using CoursesAPI.Services.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20170920171359_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CoursesAPI.Services.Models.Entities.CourseInstance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseID");

                    b.Property<string>("SemesterID");

                    b.HasKey("ID");

                    b.ToTable("CourseInstances");
                });

            modelBuilder.Entity("CoursesAPI.Services.Models.Entities.CourseTemplate", b =>
                {
                    b.Property<string>("CourseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("CourseID");

                    b.ToTable("CourseTemplates");
                });

            modelBuilder.Entity("CoursesAPI.Services.Models.Entities.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("SSN");

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CoursesAPI.Services.Models.Entities.Semester", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateBegins");

                    b.Property<DateTime>("DateEnds");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("CoursesAPI.Services.Models.Entities.TeacherRegistration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseInstanceID");

                    b.Property<string>("SSN");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.ToTable("TeacherRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
